/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DisplayPreferences = IDL.Record({
  'directionality' : IDL.Text,
  'showProfilePics' : IDL.Bool,
  'timestampFormat' : IDL.Text,
  'fontSize' : IDL.Text,
  'chatColor' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'preferences' : DisplayPreferences,
});

export const idlService = IDL.Service({
  'createProfile' : IDL.Func([IDL.Text, IDL.Text, DisplayPreferences], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateDisplayPreferences' : IDL.Func([DisplayPreferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DisplayPreferences = IDL.Record({
    'directionality' : IDL.Text,
    'showProfilePics' : IDL.Bool,
    'timestampFormat' : IDL.Text,
    'fontSize' : IDL.Text,
    'chatColor' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'preferences' : DisplayPreferences,
  });
  
  return IDL.Service({
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, DisplayPreferences],
        [],
        [],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateDisplayPreferences' : IDL.Func([DisplayPreferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };